// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA5Vk9CWl9PXtTxVXIFpDkA5HXiDDMPCc',
    appId: '1:813218655539:web:894fe5512a32dba5a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    authDomain: 't2024cs3-campusdiningapp-ac2a3.firebaseapp.com',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    measurementId: 'G-R20YSMGZ6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCebRPdq5OKFYhpOT1gVjim953q7bGwbv0',
    appId: '1:813218655539:android:d4c947b97074b805a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCguvsTj9DDS8W2iLYor7LdK0ajWVRA4q8',
    appId: '1:813218655539:ios:54994d6f6b40884aa5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    androidClientId: '813218655539-8q5k4vsdjmj3brj1bte4cktcjhot8oke.apps.googleusercontent.com',
    iosClientId: '813218655539-oa0fatjofe3pu8vl7va3ugcjgrp1mklo.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusdiningappMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCguvsTj9DDS8W2iLYor7LdK0ajWVRA4q8',
    appId: '1:813218655539:ios:54994d6f6b40884aa5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    androidClientId: '813218655539-8q5k4vsdjmj3brj1bte4cktcjhot8oke.apps.googleusercontent.com',
    iosClientId: '813218655539-oa0fatjofe3pu8vl7va3ugcjgrp1mklo.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusdiningappMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA5Vk9CWl9PXtTxVXIFpDkA5HXiDDMPCc',
    appId: '1:813218655539:web:3b0c1f85b4d21df0a5a246',
    messagingSenderId: '813218655539',
    projectId: 't2024cs3-campusdiningapp-ac2a3',
    authDomain: 't2024cs3-campusdiningapp-ac2a3.firebaseapp.com',
    storageBucket: 't2024cs3-campusdiningapp-ac2a3.firebasestorage.app',
    measurementId: 'G-X7TKLM5KHT',
  );
}
